on:
  push:
    branches:
      - master
name: Deploy to party on push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npm test
    - run: now --prod --token ${ZEIT_TOKEN}
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
    - uses: navikt/screenshots-action@1.0.5
      name: Tar bilde av forsiden
      with:
        url: https://paw.nav.party
    - uses: actions/upload-artifact@v1
      name: Laster opp skjermbilder som artifakt
      with:
        name: Screenshots
        path: screenshots
    - run: now screenshots --local-config now-screenshot.json --prod --token ${ZEIT_TOKEN}
      name: Legger skjermbilder på ZEIT/Now
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}