on:
  push:
    branches:
      - master
name: Deploy to party on push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npm test
    - run: now --prod --token ${ZEIT_TOKEN}
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}