on:
  push:
    branches:
      - master
name: Deploy to party on push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npm test
    - run: now --prod --token ${ZEIT_TOKEN}
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
    - uses: lannonbr/puppeteer-screenshot-action@1.0.0
      name: Tar bilde av forsiden
      with:
        url: https://paw.nav.party
        fullPage: true
    - name: Hente bane til skjermdump
        run: echo "::set-env name=SCREENSHOT_NAME::$(ls screenshots/*.png)"
    - uses: actions/upload-artifact@v1
      name: Laster opp skjermbilde
      with:
        name: Screenshots
        path: ${{ env.SCREENSHOT_NAME }}